import "./styles.css";
import React, { useState } from "react";

const emojiMeanings = {
  "😀": "Grinning Face",
  "😃": "Grinning Face with Big Eyes",
  "😄": "Grinning Face with Smiling Eyes",
  "😁": "Beaming Face with Smiling Eyes",
  "😆": "Grinning Squinting Face",
  "😅": "Grinning Face with Sweat",
  "😂": "Face with Tears of Joy",
  "🤣": "Rolling on the Floor Laughing",
  "😊": "Smiling Face with Smiling Eyes",
  "😇": "Smiling Face with Halo",
  "🙂": "Slightly Smiling Face",
  "🙃": "Upside-Down Face",
  "😉": "Winking Face",
  "😌": "Relieved Face",
  "😍": "Heart-Eyes",
  "😘": "Face Blowing a Kiss",
  "😗": "Kissing Face",
  "😙": "Kissing Face with Smiling Eyes",
  "😚": "Kissing Face with Closed Eyes",
  "😋": "Face Savoring Food",
  "😛": "Face with Tongue",
  "😜": "Winking Face with Tongue",
  "😝": "Squinting Face with Tongue",
  "🤪": "Zany Face",
  "🤨": "Face with Raised Eyebrow",
  "🧐": "Face with Monocle",
  "🤓": "Nerd Face",
  "😎": "Smiling Face with Sunglasses",
  "🤩": "Star-Struck",
  "🥳": "Partying Face",
  "😏": "Smirking Face",
  "😒": "Unamused Face",
  "😞": "Disappointed Face",
  "😔": "Pensive Face",
  "😟": "Worried Face",
  "😕": "Confused Face",
  "🙁": "Slightly Frowning Face",
  "☹️": "Frowning Face",
  "😣": "Persevering Face",
  "😖": "Confounded Face",
  "😫": "Tired Face",
  "😩": "Weary Face",
  "🥺": "Pleading Face",
  "😢": "Crying Face",
  "😭": "Loudly Crying Face",
  "😤": "Face with Steam From Nose",
  "😠": "Angry Face",
  "😡": "Pouting Face",
  "🤬": "Face with Symbols on Mouth",
  "😱": "Face Screaming in Fear",
  "😨": "Fearful Face",
  "😰": "Anxious Face with Sweat",
  "😥": "Sad but Relieved Face",
  "😓": "Face with Cold Sweat",
  "🤗": "Hugging Face",
  "🤔": "Thinking Face",
  "🤭": "Face with Hand Over Mouth",
  "🤫": "Shushing Face",
  "🤥": "Lying Face",
  "😶": "Face Without Mouth",
  "😐": "Neutral Face",
  "😑": "Expressionless Face",
  "😬": "Grimacing Face",
  "🙄": "Face with Rolling Eyes",
  "😯": "Hushed Face",
  "😦": "Frowning Face with Open Mouth",
  "😧": "Anguished Face",
  "😮": "Face with Open Mouth",
  "😲": "Astonished Face",
  "😴": "Sleeping Face",
  "🤤": "Drooling Face",
  "😪": "Sleepy Face",
  "😵": "Dizzy Face",
  "🤐": "Zipper-Mouth Face",
  "🤢": "Nauseated Face",
  "🤮": "Face Vomiting",
  "🤧": "Sneezing Face",
  "😷": "Face with Medical Mask",
  "🤒": "Face with Thermometer",
  "🤕": "Face with Head-Bandage",
  "🤑": "Money-Mouth Face",
  "🤠": "Cowboy Hat Face",
  "😈": "Smiling Face with Horns",
  "👿": "Angry Face with Horns",
  "👹": "Ogre",
  "👺": "Goblin",
  "🤡": "Clown Face",
  "💩": "Pile of Poo",
  "👻": "Ghost",
  "💀": "Skull",
  "☠️": "Skull and Crossbones",
  "👽": "Alien",
  "👾": "Alien Monster",
  "🤖": "Robot Face",
  "🎃": "Jack-O-Lantern",
  "😺": "Grinning Cat Face",
  "😸": "Grinning Cat Face with Smiling Eyes",
  "😹": "Cat Face with Tears of Joy",
  "😻": "Smiling Cat Face with Heart-Eyes",
  "😼": "Cat Face with Wry Smile",
  "😽": "Kissing Cat Face",
  "🙀": "Weary Cat Face",
  "😿": "Crying Cat Face",
  "😾": "Pouting Cat Face",
  "🐭": "Mouse Face",
  "🐹": "Hamster Face",
  "🐰": "Rabbit Face",
  "🐻": "Bear Face",
  "🐼": "Panda Face",
  "🐨": "Koala",
  "🐯": "Tiger Face",
  "🦁": "Lion Face",
  "🐮": "Cow Face",
  "🐷": "Pig Face",
  "🐽": "Pig Nose",
  "🐸": "Frog Face",
  "🐙": "Octopus",
  "🐵": "Monkey Face",
  "🐒": "Monkey",
  "🦍": "Gorilla",
  "🦊": "Fox Face",
  "🐔": "Chicken",
  "🐧": "Penguin",
  "🐦": "Bird",
  "🐤": "Baby Chick",
  "🐣": "Hatching Chick",
  "🐥": "Front-Facing Baby Chick",
  "🦆": "Duck",
  "🦢": "Swan",
  "🦉": "Owl",
  "🦚": "Peacock",
  "🦜": "Parrot",
  "🐢": "Turtle",
  "🦎": "Lizard",
  "🐍": "Snake",
  "🐲": "Dragon Face",
  "🐊": "Crocodile",
  "🐋": "Whale",
  "🐳": "Spouting Whale",
  "🐬": "Dolphin",
  "🐟": "Fish",
  "🐠": "Tropical Fish",
  "🐡": "Blowfish",
  "🦈": "Shark",
  "🐚": "Spiral Shell",
  "🦀": "Crab",
  "🦞": "Lobster",
  "🦐": "Shrimp",
  "🦑": "Squid",
  "❤️": "Red Heart",
  "💛": "Yellow Heart",
  "💚": "Green Heart",
  "💙": "Blue Heart",
  "💜": "Purple Heart",
  "🖤": "Black Heart",
  "💔": "Broken Heart",
  "❣️": "Heart Exclamation",
  "💕": "Two Hearts",
  "💞": "Revolving Hearts",
  "💓": "Beating Heart",
  "💗": "Growing Heart",
  "💖": "Sparkling Heart",
  "💘": "Heart with Arrow",
  "💝": "Heart with Ribbon",
  "🦠": "Microbe",
  "🧬": "DNA",
  "🔍": "Magnifying Glass Tilted Left",
  "🔎": "Magnifying Glass Tilted Right",
  "🔐": "Locked with Key",
  "🔏": "Locked with Pen",
  "🔑": "Key",
  "🔨": "Hammer",
  "🛠️": "Hammer and Wrench",
  "🪓": "Axe",
  "🔫": "Pistol",
  "🏹": "Bow and Arrow",
  "🚬": "Cigarette",
  "💣": "Bomb",
  "🔪": "Knife",
  "🗡️": "Dagger",
  "⚔️": "Crossed Swords",
  "🛡️": "Shield",
  "🚪": "Door",
  "🛏️": "Bed",
  "🛋️": "Couch and Lamp",
  "🚽": "Toilet",
  "🚿": "Shower",
  "🛁": "Bathtub",
  "🧴": "Lotion Bottle",
  "🧷": "Safety Pin",
  "🧹": "Broom",
  "🧺": "Basket",
  "🧻": "Roll of Paper",
  "🧼": "Soap",
  "⚽": "Soccer Ball",
  "🏀": "Basketball",
  "🏈": "American Football",
  "⚾": "Baseball",
  "🥎": "Softball",
  "🎾": "Tennis",
  "🏐": "Volleyball",
  "🎱": "Pool 8 Ball",
  "🏉": "Rugby Football",
  "🥏": "Flying Disc",
  "🎳": "Bowling",
  "🏏": "Cricket Game",
  "🏑": "Field Hockey",
  "🏒": "Ice Hockey",
  "🥍": "Lacrosse",
  "🏓": "Ping Pong",
  "🏸": "Badminton",
  "🥊": "Boxing Glove",
  "🥋": "Martial Arts Uniform",
  "🥅": "Goal Net",
  "⛳": "Flag in Hole",
  "⛸️": "Ice Skate",
  "🎣": "Fishing Pole",
  "🤿": "Diving Mask",
  "🎽": "Running Shirt",
  "🎿": "Skis",
  "🛷": "Sled",
  "🪂": "Parachute",
  "🎯": "Direct Hit",
  "🎮": "Video Game",
  "🕹️": "Joystick",
  "🎰": "Slot Machine",
  "🎲": "Game Die",
  "🧩": "Puzzle Piece",
  "🧸": "Teddy Bear",
  "🎈": "Balloon",
  "🎉": "Party Popper",
  "🎊": "Confetti Ball",
  "🎎": "Japanese Dolls",
  "🎏": "Carp Streamer",
  "🎐": "Wind Chime",
  "🧨": "Firecracker",
  "🎖️": "Military Medal",
  "🏆": "Trophy",
  "🏅": "Sports Medal",
  "🥇": "1st Place Medal",
  "🥈": "2nd Place Medal",
  "🥉": "3rd Place Medal",
  "🎗️": "Reminder Ribbon",
  "🎟️": "Admission Tickets",
  "🎫": "Ticket"

  // ... add more entries here ...
};

const emojiWeKnow = Object.keys(emojiMeanings);

export default function App() {
  const [meaning, setMeaning] = useState("");

  function onChangeHandler(event) {
    let userInput = event.target.value;
    let meaning = emojiMeanings[userInput];

    if (meaning === undefined) {
      setMeaning("Failure to read your emoji");
    } else {
      setMeaning(meaning);
    }
  }

  function onClickHandler(item) {
    let meaning = emojiMeanings[item];
    setMeaning(meaning);
  }

  return (
    <div className="App">
      <h1>EMOZY-PEDIA</h1>
      <input
        className="user-input"
        placeholder="Put an emozy for meaning"
        onChange={onChangeHandler}
      />
      <div className="meaning-output">{meaning}</div>

      <div className="emozies-div">
        {emojiWeKnow.map(function (item) {
          return (
            <span className="emozies" onClick={() => onClickHandler(item)}>
              {item}
            </span>
          );
        })}
      </div>
    </div>
  );
}
